"""initial schema: loan_applications, portfolio_snapshots, query_log

Revision ID: 1be5fbf106ec
Revises: 
Create Date: 2026-06-24 01:48:57.983593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be5fbf106ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_amnt', sa.Numeric(), nullable=True),
    sa.Column('int_rate', sa.Numeric(), nullable=True),
    sa.Column('annual_inc', sa.Numeric(), nullable=True),
    sa.Column('dti', sa.Numeric(), nullable=True),
    sa.Column('emp_length', sa.Numeric(), nullable=True),
    sa.Column('revol_bal', sa.Numeric(), nullable=True),
    sa.Column('revol_util', sa.Numeric(), nullable=True),
    sa.Column('mort_acc', sa.Integer(), nullable=True),
    sa.Column('int_rate_tier', sa.Integer(), nullable=True),
    sa.Column('loan_amnt_tier', sa.Integer(), nullable=True),
    sa.Column('grade_encoded', sa.Integer(), nullable=True),
    sa.Column('credit_history_years', sa.Numeric(), nullable=True),
    sa.Column('loan_to_income', sa.Numeric(), nullable=True),
    sa.Column('fico_score', sa.Numeric(), nullable=True),
    sa.Column('installment_to_income', sa.Numeric(), nullable=True),
    sa.Column('open_acc_ratio', sa.Numeric(), nullable=True),
    sa.Column('has_delinquency', sa.Boolean(), nullable=True),
    sa.Column('has_pub_rec', sa.Boolean(), nullable=True),
    sa.Column('high_inq_flag', sa.Boolean(), nullable=True),
    sa.Column('is_short_term', sa.Boolean(), nullable=True),
    sa.Column('home_OTHER', sa.Boolean(), nullable=True),
    sa.Column('home_OWN', sa.Boolean(), nullable=True),
    sa.Column('home_RENT', sa.Boolean(), nullable=True),
    sa.Column('purpose_credit_card', sa.Boolean(), nullable=True),
    sa.Column('purpose_debt_consolidation', sa.Boolean(), nullable=True),
    sa.Column('purpose_home_improvement', sa.Boolean(), nullable=True),
    sa.Column('purpose_major_purchase', sa.Boolean(), nullable=True),
    sa.Column('purpose_medical', sa.Boolean(), nullable=True),
    sa.Column('purpose_other', sa.Boolean(), nullable=True),
    sa.Column('purpose_small_business', sa.Boolean(), nullable=True),
    sa.Column('target', sa.SmallInteger(), nullable=True),
    sa.Column('default_probability', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=True),
    sa.Column('assigned_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('decision_reasons', sa.Text(), nullable=True),
    sa.Column('loaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.create_index('ix_loan_applications_decision', ['decision'], unique=False)
        batch_op.create_index('ix_loan_applications_target', ['target'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('approvals', sa.Integer(), nullable=True),
    sa.Column('rejections', sa.Integer(), nullable=True),
    sa.Column('expected_defaults', sa.Integer(), nullable=True),
    sa.Column('net_portfolio_value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('was_blocked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_log')
    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.drop_index('ix_loan_applications_target')
        batch_op.drop_index('ix_loan_applications_decision')

    op.drop_table('loan_applications')
    # ### end Alembic commands ###
