"""Top-level orchestrator for the governed NL->SQL query pipeline (Phase 4).

Pipeline: sanitize -> length check -> injection check -> Gemini SQL ->
validate/sandbox -> execute on the READ-ONLY connection (AI_DB_URL) ->
format -> audit-log on the MAIN connection (DATABASE_URL).

Security note: SQL generated by the LLM is *only ever* executed against
AI_DB_URL, which is a read-only Postgres role. The main DATABASE_URL is used
exclusively for writing the audit row to query_log.
"""
import logging
import os

import psycopg2

from app.nl_query.security import (
    check_question_length,
    is_prompt_injection,
    sanitize_question,
    validate_sql,
)
from app.nl_query.semantic_layer import MAX_RESULT_ROWS
from app.nl_query.sql_generator import generate_sql

logger = logging.getLogger(__name__)


def _base_result(question):
    """A result dict with every key present and safe defaults."""
    return {
        "question": question,
        "sql": None,
        "result": [],
        "answer": "",
        "was_blocked": False,
        "block_reason": None,
        "row_count": 0,
    }


def _execute_readonly(sql):
    """Run a validated SELECT on the read-only connection; return list of dicts."""
    conn = psycopg2.connect(os.environ.get("AI_DB_URL"))
    try:
        # Belt-and-braces: force the session read-only even though the role is.
        conn.set_session(readonly=True, autocommit=True)
        cur = conn.cursor()
        cur.execute(sql)
        rows = cur.fetchmany(MAX_RESULT_ROWS)
        columns = [desc[0] for desc in cur.description]
        return [dict(zip(columns, row)) for row in rows]
    finally:
        conn.close()


def _log_query(question, generated_sql, was_blocked):
    """Write an audit row to query_log via the MAIN connection. Never raises."""
    try:
        conn = psycopg2.connect(os.environ.get("DATABASE_URL"))
        try:
            cur = conn.cursor()
            cur.execute(
                "INSERT INTO query_log (question, generated_sql, was_blocked, "
                "created_at) VALUES (%s, %s, %s, NOW())",
                (question, generated_sql, was_blocked),
            )
            conn.commit()
        finally:
            conn.close()
    except Exception:  # logging must never crash the response
        logger.error("Failed to write query_log audit row", exc_info=True)


def _fmt_value(value):
    """Compact, readable rendering of a single cell value."""
    if value is None:
        return "null"
    if isinstance(value, float):
        return f"{value:,.2f}"
    return str(value)


def _format_answer(rows):
    """Turn result rows into a plain-English answer string."""
    n = len(rows)
    if n == 0:
        return "No matching records found."

    if n == 1:
        parts = [f"{k} = {_fmt_value(v)}" for k, v in rows[0].items()]
        return "Result: " + ", ".join(parts) + "."

    if n <= 10:
        lines = [f"Found {n} records:"]
        for row in rows:
            cells = ", ".join(f"{k}: {_fmt_value(v)}" for k, v in row.items())
            lines.append(f"  • {cells}")
        return "\n".join(lines)

    # 11–500 rows: headline + a preview of the first 5.
    lines = [f"Found {n} records. Showing the first 5:"]
    for row in rows[:5]:
        cells = ", ".join(f"{k}: {_fmt_value(v)}" for k, v in row.items())
        lines.append(f"  • {cells}")
    return "\n".join(lines)


def answer_question(question: str) -> dict:
    """Run the full governed NL->SQL pipeline and return a result dict.

    Raises ValueError if the security layer rejects the input (the route layer
    turns that into a blocked response). Any other failure is caught here and
    returned as a generic error result with was_blocked=False.
    """
    # 1 & 2 — sanitize and length-check (length check may raise ValueError,
    # which is allowed to propagate to the route as a block).
    sanitized = sanitize_question(question)
    check_question_length(sanitized)

    result = _base_result(sanitized)

    # 3 — prompt-injection block.
    if is_prompt_injection(sanitized):
        result["answer"] = "Query blocked: potential prompt injection detected."
        result["was_blocked"] = True
        result["block_reason"] = "prompt_injection"
        _log_query(sanitized, None, True)
        return result

    generated_sql = None
    try:
        # 4 — generate SQL with Gemini.
        raw_sql = generate_sql(sanitized)

        # 5 — model declined.
        if raw_sql.strip() == "CANNOT_ANSWER":
            result["answer"] = (
                "This question cannot be answered from the loan portfolio data."
            )
            _log_query(sanitized, None, False)
            return result

        # 6 — validate / sandbox (may raise ValueError -> propagates to route).
        safe_sql = validate_sql(raw_sql)
        generated_sql = safe_sql

        # 7 — execute on the read-only connection.
        rows = _execute_readonly(safe_sql)

        # 8 — format the answer.
        result["sql"] = safe_sql
        result["result"] = rows
        result["row_count"] = len(rows)
        result["answer"] = _format_answer(rows)

        # 9 — audit log.
        _log_query(sanitized, safe_sql, False)
        return result

    except ValueError:
        # A security-layer rejection (e.g. from validate_sql). Log it as
        # blocked and re-raise so the route returns was_blocked=True.
        _log_query(sanitized, generated_sql, True)
        raise

    except Exception:
        # Any non-security failure (Gemini error, DB error, etc.).
        logger.error("NL query pipeline failed", exc_info=True)
        _log_query(sanitized, generated_sql, False)
        result["answer"] = (
            "An error occurred processing your query. Please try rephrasing."
        )
        result["was_blocked"] = False
        return result
